# 최종 컷오버: 호스트 8000번을 쿠버네티스 NodePort(30080)로 매핑.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8000
        protocol: TCP
